### ISSUE TITLE
ValueError: Expected n_neighbors <= n_samples,  but n_samples = 33, n_neighbors = 41

### ISSUE THREAD

**Issue by jingydz** [esteinig/netviewP#2]
`$ netview.py -f file_prefix.ped -a hebing.csv -p

[15:54:12]	---------------------------------
[15:54:12]	         NETVIEW P v.0.7.1         
[15:54:12]	---------------------------------
[15:54:12]	File = FILE_PREFIX.PED
[15:54:20]	N = 33
[15:54:20]	SNPs = 393186
[15:54:20]	Ploidy = DIPLOID
[15:54:20]	---------------------------------
[15:54:20]	Quality Control = FALSE
[15:54:20]	Distance = ASD
[15:55:12]	Minimum Spanning Tree = TRUE
[15:55:12]	Nearest Neighbour = BRUTE
[15:55:12]	k = 10 - 40 (by 10)
[15:55:12]	---------------------------------
[15:55:13]	              k=30
[15:55:13]	              k=20
[15:55:13]	              k=10
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/data/users/zhangjingjing/anaconda2/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/data/users/zhangjingjing/netviewp/netviewP/program/linux/0.7.1/netview.py", line 160, in netview
    adj_knn = nbrs.kneighbors_graph(matrix).toarray()
  File "/data/users/zhangjingjing/anaconda2/lib/python3.6/site-packages/sklearn/neighbors/base.py", line 556, in kneighbors_graph
    A_ind = self.kneighbors(X, n_neighbors, return_distance=False)
  File "/data/users/zhangjingjing/anaconda2/lib/python3.6/site-packages/sklearn/neighbors/base.py", line 415, in kneighbors
    (train_size, n_neighbors)
ValueError: Expected n_neighbors <= n_samples,  but n_samples = 33, n_neighbors = 41
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/users/zhangjingjing/netviewp/netviewP/program/linux/0.7.1/netview.py", line 882, in <module>
    main()
  File "/data/users/zhangjingjing/netviewp/netviewP/program/linux/0.7.1/netview.py", line 106, in main
    html=commands.arg_dict['web'])
  File "/data/users/zhangjingjing/netviewp/netviewP/program/linux/0.7.1/netview.py", line 871, in runNetView
    result = item.get()
  File "/data/users/zhangjingjing/anaconda2/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
ValueError: Expected n_neighbors <= n_samples,  but n_samples = 33, n_neighbors = 41
`
during I run this code, I got the error
could you tell me what's wrong?
thank you very much!

**Comment by esteinig** [comment]
You have selected a larger `k` than your `n`, `k` needs to be < 33.

Btw 30 samples are very much on the minimum side for NetView. Because it's a machine learning approach, large marker and same sizes are more robust and you should probably not use NetView as a primary means of analysis in this case, i.e. supplement with Structure or Admixture.
